# Generated by Django 6.0.4 on 2026-04-29 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0014_historical_records'),
        ('client', '0006_client_cases_clien_name_119a2d_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='casenumber',
            index=models.Index(fields=['number'], name='cases_casen_number_101333_idx'),
        ),
        migrations.AddIndex(
            model_name='caseparty',
            index=models.Index(fields=['client'], name='cases_casep_client__76e55d_idx'),
        ),
    ]
