# Generated by Django 6.0.4 on 2026-05-02 23:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0015_casenumber_cases_casen_number_101333_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='caseaccessgrant',
            unique_together={('case', 'grantee')},
        ),
        migrations.AlterUniqueTogether(
            name='caseassignment',
            unique_together={('case', 'lawyer')},
        ),
        migrations.AddIndex(
            model_name='caseaccessgrant',
            index=models.Index(fields=['grantee'], name='cases_casea_grantee_5cc332_idx'),
        ),
        migrations.AddIndex(
            model_name='caseassignment',
            index=models.Index(fields=['lawyer'], name='cases_casea_lawyer__3bf353_idx'),
        ),
        migrations.AddIndex(
            model_name='caselogattachment',
            index=models.Index(fields=['log'], name='cases_casel_log_id_e9778e_idx'),
        ),
        migrations.AddIndex(
            model_name='caselogversion',
            index=models.Index(fields=['log'], name='cases_casel_log_id_12f3b6_idx'),
        ),
        migrations.AddIndex(
            model_name='caselogversion',
            index=models.Index(fields=['actor'], name='cases_casel_actor_i_eab82d_idx'),
        ),
    ]
