# Generated by Django 6.0.5 on 2026-05-10 03:31

import apps.cases.models.log
import apps.core.filesystem.storage
import apps.core.filesystem.upload_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0016_add_indexes_and_unique_constraints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caselogattachment',
            name='file',
            field=models.FileField(storage=apps.core.filesystem.storage.KeepOriginalNameStorage(), upload_to=apps.core.filesystem.upload_paths.DatedUUIDPath('case_logs'), validators=[apps.cases.models.log.validate_log_attachment], verbose_name='相关文书'),
        ),
        migrations.AlterField(
            model_name='casenumber',
            name='document_file',
            field=models.FileField(blank=True, help_text='上传PDF格式的裁判文书，用于自动提取执行依据主文', null=True, upload_to=apps.core.filesystem.upload_paths.DatedUUIDPath('case_documents'), verbose_name='裁判文书文件'),
        ),
    ]
