# Generated by Django 6.0.5 on 2026-05-16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0017_alter_caselogattachment_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRecordCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('is_income', models.BooleanField(default=True, help_text='True=收入类别（如回款），False=支出类别（如差旅费）', verbose_name='是否收入类别')),
                ('is_system', models.BooleanField(default=False, help_text='系统内置类别不可删除，用户自定义的类别可删除', verbose_name='系统内置')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序顺序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '款项用途',
                'verbose_name_plural': '款项用途',
                'ordering': ['is_income', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CaseLogBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('original_content', models.TextField(verbose_name='原始日志内容')),
                ('case_ids', models.JSONField(default=list, help_text='参与批量创建的案件ID列表', verbose_name='案件ID列表')),
                ('reminder_type', models.CharField(blank=True, max_length=64, null=True, verbose_name='提醒类型')),
                ('reminder_time', models.DateTimeField(blank=True, null=True, verbose_name='提醒时间')),
                ('has_expense_split', models.BooleanField(default=False, verbose_name='包含费用分摊')),
                ('expense_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='费用总金额')),
                ('expense_split_count', models.IntegerField(blank=True, help_text='费用分摊到的案件数量，可小于case_ids数量', null=True, verbose_name='费用分摊份数')),
                ('expense_per_case', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='每案件分摊金额')),
                ('expense_record_date', models.DateField(blank=True, null=True, verbose_name='费用发生日期')),
                ('total_cases', models.IntegerField(default=0, verbose_name='总案件数')),
                ('success_count', models.IntegerField(default=0, verbose_name='成功数')),
                ('fail_count', models.IntegerField(default=0, verbose_name='失败数')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='log_batches', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('expense_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_batches', to='cases.paymentrecordcategory', verbose_name='费用类型')),
            ],
            options={
                'verbose_name': '批量日志记录',
                'verbose_name_plural': '批量日志记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='caselog',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='cases.caselogbatch', verbose_name='批量日志来源'),
        ),
        migrations.AddField(
            model_name='caselog',
            name='is_split_child',
            field=models.BooleanField(default=False, help_text='标记是否从批量操作分拆而来', verbose_name='是否分拆子记录'),
        ),
        migrations.AddField(
            model_name='caselog',
            name='split_count',
            field=models.IntegerField(default=1, help_text='如99个案件分摊，则为99', verbose_name='分摊份数'),
        ),
        migrations.AddField(
            model_name='caselog',
            name='split_source_id',
            field=models.IntegerField(blank=True, help_text='指向原始批量创建的日志ID', null=True, verbose_name='分拆来源日志ID'),
        ),
        migrations.CreateModel(
            name='CasePaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='金额')),
                ('record_date', models.DateField(verbose_name='发生日期')),
                ('is_income', models.BooleanField(default=True, help_text='True=收入/回款, False=支出/费用', verbose_name='是否收入')),
                ('payment_method', models.CharField(blank=True, choices=[('bank_transfer', '银行转账'), ('court_enforcement', '法院执行'), ('cash', '现金'), ('online_payment', '线上支付'), ('check', '支票'), ('other', '其他')], max_length=32, null=True, verbose_name='支付方式')),
                ('payer_payee_name', models.CharField(blank=True, default='', help_text='收入时填写付款方名称，支出时填写收款方名称', max_length=255, verbose_name='付款方/收款方')),
                ('source_type', models.CharField(choices=[('manual', '手动录入'), ('contract_payment', '合同收款记录'), ('client_payment', '客户回款记录'), ('log_batch_split', '批量日志分摊')], default='manual', max_length=32, verbose_name='来源类型')),
                ('source_id', models.IntegerField(blank=True, help_text='关联的原始记录ID，如合同收款ID', null=True, verbose_name='来源ID')),
                ('is_split', models.BooleanField(default=False, help_text='标记是否从批量操作分摊而来', verbose_name='是否分摊记录')),
                ('split_count', models.IntegerField(default=1, help_text='如99个案件分摊，则为99', verbose_name='分摊份数')),
                ('has_receipt', models.BooleanField(default=False, verbose_name='是否有凭证')),
                ('receipt_note', models.CharField(blank=True, default='', max_length=500, verbose_name='凭证说明')),
                ('description', models.TextField(blank=True, default='', verbose_name='说明/备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_records', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_records', to='cases.case', verbose_name='案件')),
                ('case_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_records', to='cases.casenumber', verbose_name='关联案号')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_records', to='cases.paymentrecordcategory', verbose_name='款项用途')),
                ('split_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='split_children', to='cases.casepaymentrecord', verbose_name='分摊来源记录')),
            ],
            options={
                'verbose_name': '案件收支记录',
                'verbose_name_plural': '案件收支记录',
                'ordering': ['-record_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='paymentrecordcategory',
            index=models.Index(fields=['is_income'], name='cases_payme_is_incom_f7b0a5_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrecordcategory',
            index=models.Index(fields=['is_system'], name='cases_payme_is_syst_3d9f8c_idx'),
        ),
        migrations.AddIndex(
            model_name='caselogbatch',
            index=models.Index(fields=['actor', '-created_at'], name='cases_casel_actor__f5e8a7_idx'),
        ),
        migrations.AddIndex(
            model_name='caselogbatch',
            index=models.Index(fields=['-created_at'], name='cases_casel_created_4f7e2b_idx'),
        ),
        migrations.AddIndex(
            model_name='casepaymentrecord',
            index=models.Index(fields=['case', '-record_date'], name='cases_casep_case_id_d4e8c1_idx'),
        ),
        migrations.AddIndex(
            model_name='casepaymentrecord',
            index=models.Index(fields=['category'], name='cases_casep_categor_6a8b2d_idx'),
        ),
        migrations.AddIndex(
            model_name='casepaymentrecord',
            index=models.Index(fields=['is_income'], name='cases_casep_is_inco_9c3d5e_idx'),
        ),
        migrations.AddIndex(
            model_name='casepaymentrecord',
            index=models.Index(fields=['source_type'], name='cases_casep_source__7b1f4f_idx'),
        ),
        migrations.AddIndex(
            model_name='casepaymentrecord',
            index=models.Index(fields=['is_split'], name='cases_casep_is_spl_2a8c6d_idx'),
        ),
    ]
