# Generated by Django 6.0.5 on 2026-05-16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0018_add_payment_and_batch_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='caselogbatch',
            name='has_income_split',
            field=models.BooleanField(default=False, verbose_name='包含收入分摊'),
        ),
        migrations.AddField(
            model_name='caselogbatch',
            name='income_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='收入总金额'),
        ),
        migrations.AddField(
            model_name='caselogbatch',
            name='income_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='income_log_batches', to='cases.paymentrecordcategory', verbose_name='收入类型'),
        ),
        migrations.AddField(
            model_name='caselogbatch',
            name='income_per_case',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='每案件收入金额'),
        ),
        migrations.AddField(
            model_name='caselogbatch',
            name='income_record_date',
            field=models.DateField(blank=True, null=True, verbose_name='收入发生日期'),
        ),
        migrations.AddField(
            model_name='caselogbatch',
            name='income_split_count',
            field=models.IntegerField(blank=True, help_text='收入分摊到的案件数量，可小于case_ids数量', null=True, verbose_name='收入分摊份数'),
        ),
        migrations.AlterField(
            model_name='caselogbatch',
            name='expense_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_log_batches', to='cases.paymentrecordcategory', verbose_name='费用类型'),
        ),
    ]
