# Generated by Django 6.0.5 on 2026-05-24 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0019_backfill_original_filename'),
    ]

    operations = [
        # Clean up leftover columns/tables from deleted CaseGroup migration (idempotent)
        migrations.RunSQL(
            sql=[
                "ALTER TABLE cases_case DROP COLUMN IF EXISTS case_group_id;",
                "ALTER TABLE cases_case DROP COLUMN IF EXISTS group_sequence;",
                "ALTER TABLE cases_historicalcase DROP COLUMN IF EXISTS case_group_id;",
                "ALTER TABLE cases_historicalcase DROP COLUMN IF EXISTS group_sequence;",
                "DROP TABLE IF EXISTS cases_casegroup;",
            ],
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AddField(
            model_name='case',
            name='previous_case',
            field=models.ForeignKey(blank=True, help_text='该案的前一个审理阶段，如二审案件指向前一审案件', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_cases', to='cases.case', verbose_name='前序案件'),
        ),
        migrations.AddField(
            model_name='historicalcase',
            name='previous_case',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='该案的前一个审理阶段，如二审案件指向前一审案件', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cases.case', verbose_name='前序案件'),
        ),
    ]
