# Generated by Codex on 2026-05-29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cases", "0019_backfill_original_filename"),
        ("cases", "0019_caselogattachment_original_filename"),
    ]

    operations = [
        migrations.AddField(
            model_name="case",
            name="previous_case",
            field=models.ForeignKey(
                blank=True,
                help_text="该案的前一个审理阶段，如二审案件指向前一审案件",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="next_cases",
                to="cases.case",
                verbose_name="前序案件",
            ),
        ),
        migrations.AddField(
            model_name="historicalcase",
            name="previous_case",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="该案的前一个审理阶段，如二审案件指向前一审案件",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="cases.case",
                verbose_name="前序案件",
            ),
        ),
    ]
