# Generated by Django 6.0.5 on 2026-05-24 09:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0021_add_previous_case_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='start_date',
            field=models.DateField(default=datetime.date.today, verbose_name='收案日期'),
        ),
        migrations.AlterField(
            model_name='historicalcase',
            name='start_date',
            field=models.DateField(default=datetime.date.today, verbose_name='收案日期'),
        ),
    ]