# Generated by Django 6.0.5 on 2026-06-03 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0022_add_unique_together_supervising_authority'),
        ('core', '0007_cloud_storage_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='casefolderbinding',
            name='storage_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cloudstorageaccount', verbose_name='云存储账号'),
        ),
        migrations.AddField(
            model_name='casefolderbinding',
            name='storage_type',
            field=models.CharField(choices=[('local', '本地文件系统'), ('webdav', '坚果云 WebDAV'), ('onedrive', 'OneDrive')], default='local', max_length=20, verbose_name='存储类型'),
        ),
    ]
