# Generated by Django 6.0.5 on 2026-06-14 15:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0025_alter_casefolderbinding_storage_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CasePaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('income', '收入'), ('expense', '支出')], max_length=16, verbose_name='收支方向')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='金额')),
                ('purpose', models.CharField(choices=[('counterparty_payment', '相对方主动支付'), ('enforcement_recovery', '执行回款'), ('court_fee_refund', '法院退还诉讼费'), ('settlement', '和解款'), ('court_fee', '诉讼费'), ('preservation_fee', '诉讼保全费'), ('property_preservation_fee', '财产保全费'), ('announcement_fee', '公告费'), ('execution_fee', '执行费'), ('appraisal_fee', '鉴定费'), ('attorney_fee', '律师费'), ('travel_fee', '差旅费'), ('investigation_fee', '调查费'), ('property_insurance_fee', '财产保险费'), ('guarantee_fee', '保函费'), ('notary_fee', '公证费'), ('assessment_fee', '评估费'), ('express_fee', '快递费'), ('other_expense', '其他费用')], max_length=64, verbose_name='款项用途')),
                ('payment_method', models.CharField(choices=[('bank_transfer', '银行转账'), ('court_enforcement', '法院执行'), ('cash', '现金'), ('online_payment', '在线支付'), ('check', '支票'), ('other', '其他')], default='bank_transfer', max_length=32, verbose_name='支付方式')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='收支日期')),
                ('note', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_records', to='cases.case', verbose_name='关联案件')),
                ('case_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_records', to='cases.caselog', verbose_name='关联日志')),
            ],
            options={
                'verbose_name': '案件收支记录',
                'verbose_name_plural': '案件收支记录',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['case'], name='cases_casep_case_id_4b738b_idx'), models.Index(fields=['case_log'], name='cases_casep_case_lo_e4986b_idx'), models.Index(fields=['direction'], name='cases_casep_directi_214831_idx'), models.Index(fields=['date'], name='cases_casep_date_8cda58_idx')],
            },
        ),
    ]
