# Generated by Django 6.0.6 on 2026-06-15 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0026_add_performance_indexes_round2'),
        ('cases', '0026_case_payment_record'),
    ]

    operations = [
    ]
