# Generated by Django 6.0.6 on 2026-06-15 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0027_alter_payment_record_optional_fields'),
        ('cases', '0027_merge_20260615_1422'),
    ]

    operations = [
    ]
