# Generated by Django 6.0.5 on 2026-06-20 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0032_add_pg_trgm_gin_index'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='casenumber',
            new_name='caseno_gin_trgm',
            old_name='cases_casenumber_number_gin_trgm',
        ),
    ]
