# Generated by Django 6.0.5 on 2026-05-10 03:31

import apps.core.filesystem.upload_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatrecordexporttask',
            name='output_file',
            field=models.FileField(blank=True, null=True, upload_to=apps.core.filesystem.upload_paths.EntityIdPath('chat_records/exports', 'pk'), verbose_name='导出文件'),
        ),
        migrations.AlterField(
            model_name='chatrecordrecording',
            name='video',
            field=models.FileField(upload_to=apps.core.filesystem.upload_paths.EntityIdPath('chat_records/recordings', 'pk'), verbose_name='录屏文件'),
        ),
        migrations.AlterField(
            model_name='chatrecordscreenshot',
            name='image',
            field=models.ImageField(upload_to=apps.core.filesystem.upload_paths.EntityIdPath('chat_records/screenshots', 'pk'), verbose_name='截图'),
        ),
    ]
