# Generated by Django 6.0.4 on 2026-04-29 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0015_casenumber_cases_casen_number_101333_idx_and_more'),
        ('contracts', '0026_contractparty_contracts_c_client__6764de_idx'),
        ('reminders', '0003_historical_records'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='reminder',
            index=models.Index(fields=['contract'], name='reminders_r_contrac_f13768_idx'),
        ),
        migrations.AddIndex(
            model_name='reminder',
            index=models.Index(fields=['case'], name='reminders_r_case_id_11a9db_idx'),
        ),
        migrations.AddIndex(
            model_name='reminder',
            index=models.Index(fields=['case_log'], name='reminders_r_case_lo_5b9d79_idx'),
        ),
    ]
