# Generated by Django 6.0.6 on 2026-06-26 12:34
# Fixed: use SeparateDatabaseAndState to avoid UniqueViolation when
# the table already exists (e.g. from a partial previous migrate).

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


CREATE_TABLE_SQL = """
CREATE TABLE IF NOT EXISTS reminders_calendarfeedtoken (
    id          BIGSERIAL PRIMARY KEY,
    token       VARCHAR(64) NOT NULL UNIQUE,
    created_at  TIMESTAMPTZ NOT NULL,
    updated_at  TIMESTAMPTZ NOT NULL,
    user_id     BIGINT NOT NULL UNIQUE
                REFERENCES "organization_lawyer" (id)
                ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED
);
CREATE UNIQUE INDEX IF NOT EXISTS
    reminders_calendarfeedtoken_token_uniq
    ON reminders_calendarfeedtoken (token);
CREATE UNIQUE INDEX IF NOT EXISTS
    reminders_calendarfeedtoken_user_id_uniq
    ON reminders_calendarfeedtoken (user_id);
"""

DROP_TABLE_SQL = "DROP TABLE IF EXISTS reminders_calendarfeedtoken;"


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0007_remove_reminder_reminders_type_due_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='CalendarFeedToken',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('token', models.CharField(max_length=64, unique=True, verbose_name='订阅令牌')),
                        ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                        ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                        ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_feed_token', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                    ],
                    options={
                        'verbose_name': '日历订阅令牌',
                        'verbose_name_plural': '日历订阅令牌',
                    },
                ),
            ],
            database_operations=[
                migrations.RunSQL(CREATE_TABLE_SQL, DROP_TABLE_SQL),
            ],
        ),
    ]
