# Generated by Django 6.0.4 on 2026-05-02 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story_viz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storyanimation',
            name='llm_model',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='LLM 模型'),
        ),
    ]
