# Generated by Django 6.0.4 on 2026-05-02 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story_viz', '0002_add_llm_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storyanimation',
            name='viz_type',
            field=models.CharField(choices=[('timeline', '时间线'), ('relationship', '人物关系图'), ('claim_judgment', '诉求 vs 判决')], default='timeline', max_length=32, verbose_name='可视化类型'),
        ),
    ]
