# Generated by Django 6.0.4 on 2026-05-07 08:45

import apps.core.filesystem.upload_paths
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocConverterTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Doc Converter', max_length=64)),
            ],
            options={
                'verbose_name': 'DOC 转 DOCX',
                'verbose_name_plural': 'DOC 转 DOCX',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DocConverterJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', '待处理'), ('converting', '转换中'), ('packing', '打包中'), ('completed', '已完成'), ('failed', '失败'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('total_files', models.PositiveIntegerField(default=0, verbose_name='总文件数')),
                ('converted_files', models.PositiveIntegerField(default=0, verbose_name='已转换数')),
                ('failed_files', models.PositiveIntegerField(default=0, verbose_name='失败数')),
                ('progress', models.PositiveIntegerField(default=0, verbose_name='进度(0-100)')),
                ('cancel_requested', models.BooleanField(default=False, verbose_name='请求取消')),
                ('task_id', models.CharField(blank=True, default='', max_length=255, verbose_name='Django Q2 任务ID')),
                ('output_zip', models.FileField(blank=True, default='', upload_to=apps.core.filesystem.upload_paths.DatedUUIDPath('doc_converter_zip'), verbose_name='结果ZIP')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doc_converter_jobs', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': 'DOC 转换任务',
                'verbose_name_plural': 'DOC 转换任务',
                'db_table': 'doc_converter_job',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocConverterItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_name', models.CharField(max_length=500, verbose_name='原始文件名')),
                ('source_file', models.FileField(upload_to=apps.core.filesystem.upload_paths.DatedUUIDPath('doc_converter_source'), verbose_name='源文件')),
                ('converted_file', models.FileField(blank=True, default='', upload_to=apps.core.filesystem.upload_paths.DatedUUIDPath('doc_converter_output'), verbose_name='转换后文件')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('converting', '转换中'), ('packing', '打包中'), ('completed', '已完成'), ('failed', '失败'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('error', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('duration_ms', models.FloatField(blank=True, null=True, verbose_name='耗时(ms)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='doc_converter.docconverterjob', verbose_name='任务')),
            ],
            options={
                'verbose_name': 'DOC 转换项',
                'verbose_name_plural': 'DOC 转换项',
                'db_table': 'doc_converter_item',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='docconverterjob',
            index=models.Index(fields=['status', '-created_at'], name='doc_convert_status_182754_idx'),
        ),
    ]
