# Generated by Django 6.0.6 on 2026-06-14 00:39

import apps.image_rotation.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageRotationTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Image Rotation', max_length=64)),
            ],
            options={
                'verbose_name': '图片自动旋转',
                'verbose_name_plural': '图片自动旋转',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ImageRotationJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=200, verbose_name='任务名称')),
                ('status', models.CharField(choices=[('completed', '已完成'), ('failed', '失败')], default='completed', max_length=20, verbose_name='状态')),
                ('total_pages', models.PositiveIntegerField(default=0, verbose_name='总页数')),
                ('export_zip', models.FileField(blank=True, default='', upload_to=apps.image_rotation.models._JobExportPath(), verbose_name='导出 ZIP')),
                ('export_pdf', models.FileField(blank=True, default='', upload_to=apps.image_rotation.models._JobExportPath(), verbose_name='导出 PDF')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='image_rotation_jobs', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '图片旋转任务',
                'verbose_name_plural': '图片旋转任务',
                'db_table': 'image_rotation_job',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImageRotationPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=500, verbose_name='原始文件名')),
                ('source_image', models.FileField(upload_to=apps.image_rotation.models._JobSourcePath(), verbose_name='源图')),
                ('page_number', models.PositiveIntegerField(default=0, verbose_name='页码')),
                ('detected_rotation', models.IntegerField(default=0, verbose_name='检测角度')),
                ('detection_confidence', models.FloatField(default=0.0, verbose_name='置信度')),
                ('ocr_text', models.TextField(blank=True, default='', verbose_name='OCR 文本')),
                ('suggested_filename', models.CharField(blank=True, default='', max_length=500, verbose_name='建议文件名')),
                ('source_type', models.CharField(default='image', help_text="'image' 或 'pdf_page'", max_length=20, verbose_name='来源类型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='image_rotation.imagerotationjob', verbose_name='任务')),
            ],
            options={
                'verbose_name': '图片旋转页面',
                'verbose_name_plural': '图片旋转页面',
                'db_table': 'image_rotation_page',
                'ordering': ['page_number'],
            },
        ),
        migrations.AddIndex(
            model_name='imagerotationjob',
            index=models.Index(fields=['status', '-created_at'], name='image_rotat_status_8d7bf7_idx'),
        ),
    ]
