# Generated by Django 6.0.6 on 2026-06-14 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_rotation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagerotationjob',
            name='export_pdf',
        ),
        migrations.RemoveField(
            model_name='imagerotationjob',
            name='export_zip',
        ),
        migrations.AddField(
            model_name='imagerotationjob',
            name='export_pdf_url',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='导出 PDF URL'),
        ),
        migrations.AddField(
            model_name='imagerotationjob',
            name='export_zip_url',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='导出 ZIP URL'),
        ),
    ]
