# Generated by Django 6.0.6 on 2026-06-14 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_rotation', '0002_remove_imagerotationjob_export_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagerotationpage',
            name='onnx_rotation',
            field=models.IntegerField(default=0, verbose_name='ONNX自动旋转角度'),
        ),
    ]
