# Generated by Django 6.0.4 on 2026-05-06 14:06

import apps.core.filesystem.upload_paths
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workbench', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_type', models.CharField(default='doc_analysis', help_text='doc_analysis, 未来可扩展其他类型', max_length=50, verbose_name='任务类型')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('running', '运行中'), ('completed', '已完成'), ('failed', '失败'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('prompt', models.TextField(verbose_name='分析要求')),
                ('llm_model', models.CharField(blank=True, default='', max_length=255, verbose_name='LLM 模型')),
                ('total_items', models.PositiveIntegerField(default=0, verbose_name='总文件数')),
                ('completed_items', models.PositiveIntegerField(default=0, verbose_name='已完成数')),
                ('failed_items', models.PositiveIntegerField(default=0, verbose_name='失败数')),
                ('progress', models.PositiveIntegerField(default=0, help_text='0-100', verbose_name='进度')),
                ('cancel_requested', models.BooleanField(default=False, verbose_name='请求取消')),
                ('task_id', models.CharField(blank=True, default='', max_length=255, verbose_name='Django Q2 任务ID')),
                ('summary', models.TextField(blank=True, default='', verbose_name='汇总结论')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='元数据')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_jobs', to='workbench.workbenchsession', verbose_name='关联会话')),
            ],
            options={
                'verbose_name': '批量任务',
                'verbose_name_plural': '批量任务',
                'db_table': 'workbench_batch_job',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BatchJobItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=500, verbose_name='文件名')),
                ('file', models.FileField(upload_to=apps.core.filesystem.upload_paths.DatedUUIDPath('workbench_batch'), verbose_name='文件')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('running', '运行中'), ('completed', '已完成'), ('failed', '失败'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('result', models.TextField(blank=True, default='', verbose_name='分析结论')),
                ('error', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('duration_ms', models.FloatField(blank=True, null=True, verbose_name='耗时(ms)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='workbench.batchjob', verbose_name='所属任务')),
            ],
            options={
                'verbose_name': '批量任务子项',
                'verbose_name_plural': '批量任务子项',
                'db_table': 'workbench_batch_job_item',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='batchjob',
            index=models.Index(fields=['session', '-created_at'], name='workbench_b_session_ffe6c8_idx'),
        ),
        migrations.AddIndex(
            model_name='batchjob',
            index=models.Index(fields=['status'], name='workbench_b_status_f1b76c_idx'),
        ),
    ]
