# Generated by Django 6.0.4 on 2026-05-07 05:57

import apps.core.filesystem.upload_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workbench', '0002_batch_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchjob',
            name='summary_file',
            field=models.FileField(blank=True, default='', upload_to=apps.core.filesystem.upload_paths.DatedUUIDPath('workbench_summary'), verbose_name='汇总文件'),
        ),
    ]
