# Generated by Django 6.0.4 on 2026-05-07 13:21

import apps.core.filesystem.upload_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workbench', '0004_add_batch_progress_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='batchjob',
            name='detail_zip_file',
            field=models.FileField(blank=True, default='', upload_to=apps.core.filesystem.upload_paths.DatedUUIDPath('workbench_detail'), verbose_name='分析详情 ZIP'),
        ),
    ]
