# Generated by Django 6.0.5 on 2026-05-10 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workbench', '0005_batchjob_detail_zip_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='workbenchsession',
            name='storage_bytes',
            field=models.PositiveIntegerField(default=0, help_text='该会话所有消息内容的总字节数（UTF-8）', verbose_name='存储字节数'),
        ),
    ]
