# Generated by Django 6.0.5 on 2026-06-03 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_systemconfig_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudStorageAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='如：坚果云-工作空间', max_length=100, verbose_name='存储名称')),
                ('storage_type', models.CharField(choices=[('local', '本地文件系统'), ('webdav', '坚果云 WebDAV'), ('onedrive', 'OneDrive')], default='local', max_length=20, verbose_name='存储类型')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('webdav_url', models.URLField(blank=True, default='https://dav.jianguoyun.com/dav/', verbose_name='WebDAV 地址')),
                ('webdav_username', models.CharField(blank=True, default='', max_length=255, verbose_name='WebDAV 用户名')),
                ('webdav_password', models.CharField(blank=True, default='', max_length=512, verbose_name='WebDAV 应用密码（加密存储）')),
                ('webdav_root_path', models.CharField(blank=True, default='/', max_length=500, verbose_name='WebDAV 根路径')),
                ('onedrive_client_id', models.CharField(blank=True, default='', max_length=255, verbose_name='Azure AD Client ID')),
                ('onedrive_tenant_id', models.CharField(blank=True, default='consumers', max_length=255, verbose_name='Azure AD Tenant ID')),
                ('onedrive_root_path', models.CharField(blank=True, default='/', max_length=500, verbose_name='OneDrive 根路径')),
                ('onedrive_access_token', models.TextField(blank=True, default='', verbose_name='OneDrive Access Token（加密）')),
                ('onedrive_refresh_token', models.TextField(blank=True, default='', verbose_name='OneDrive Refresh Token（加密）')),
                ('onedrive_token_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Token 过期时间')),
                ('local_root_path', models.CharField(blank=True, default='/', max_length=1000, verbose_name='本地根路径')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '云存储账号',
                'verbose_name_plural': '云存储账号',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['storage_type'], name='core_clouds_storage_fe624d_idx'), models.Index(fields=['is_active'], name='core_clouds_is_acti_2cfd68_idx')],
            },
        ),
    ]
