# Generated by Django 6.0.6 on 2026-06-07 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_cloudstorageaccount_dropbox_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudstorageaccount',
            name='dropbox_pending_device_code',
            field=models.TextField(blank=True, default='', verbose_name='Dropbox 待轮询 Device Code'),
        ),
        migrations.AddField(
            model_name='cloudstorageaccount',
            name='dropbox_pending_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Dropbox Device Code 过期时间'),
        ),
        migrations.AddField(
            model_name='cloudstorageaccount',
            name='onedrive_pending_device_code',
            field=models.TextField(blank=True, default='', help_text='授权流程中临时存储，进程重启后可恢复轮询', verbose_name='OneDrive 待轮询 Device Code'),
        ),
        migrations.AddField(
            model_name='cloudstorageaccount',
            name='onedrive_pending_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Device Code 过期时间'),
        ),
    ]
