# Generated by Django 6.0.4 on 2026-05-07 13:13

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0016_add_indexes_and_unique_constraints'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalCaseContact',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('role', models.CharField(choices=[('presiding_judge', '审判长'), ('judge', '审判员/法官'), ('clerk', '书记员'), ('judge_assistant', '法官助理'), ('prosecutor', '检察官'), ('police', '警官'), ('arbitrator', '仲裁员'), ('mediator', '调解员'), ('other', '其他')], default='other', max_length=32, verbose_name='角色')),
                ('phone', models.CharField(blank=True, max_length=32, null=True, verbose_name='电话')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='收件地址')),
                ('stage', models.CharField(blank=True, choices=[('first_trial', '一审'), ('second_trial', '二审'), ('enforcement', '执行'), ('labor_arbitration', '劳动仲裁'), ('administrative_review', '行政复议'), ('private_prosecution', '自诉'), ('investigation', '侦查'), ('prosecution_review', '审查起诉'), ('retrial_first', '重审一审'), ('retrial_second', '重审二审'), ('apply_retrial', '申请再审'), ('rehearing_first', '再审一审'), ('rehearing_second', '再审二审'), ('review', '提审'), ('death_penalty_review', '死刑复核程序'), ('petition', '申诉'), ('apply_protest', '申请抗诉'), ('petition_protest', '申诉抗诉')], max_length=64, null=True, verbose_name='所属阶段')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新时间')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('authority', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cases.supervisingauthority', verbose_name='主管机关')),
                ('case', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cases.case', verbose_name='案件')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical 案件工作人员',
                'verbose_name_plural': 'historical 案件工作人员',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='CaseContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('role', models.CharField(choices=[('presiding_judge', '审判长'), ('judge', '审判员/法官'), ('clerk', '书记员'), ('judge_assistant', '法官助理'), ('prosecutor', '检察官'), ('police', '警官'), ('arbitrator', '仲裁员'), ('mediator', '调解员'), ('other', '其他')], default='other', max_length=32, verbose_name='角色')),
                ('phone', models.CharField(blank=True, max_length=32, null=True, verbose_name='电话')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='收件地址')),
                ('stage', models.CharField(blank=True, choices=[('first_trial', '一审'), ('second_trial', '二审'), ('enforcement', '执行'), ('labor_arbitration', '劳动仲裁'), ('administrative_review', '行政复议'), ('private_prosecution', '自诉'), ('investigation', '侦查'), ('prosecution_review', '审查起诉'), ('retrial_first', '重审一审'), ('retrial_second', '重审二审'), ('apply_retrial', '申请再审'), ('rehearing_first', '再审一审'), ('rehearing_second', '再审二审'), ('review', '提审'), ('death_penalty_review', '死刑复核程序'), ('petition', '申诉'), ('apply_protest', '申请抗诉'), ('petition_protest', '申诉抗诉')], max_length=64, null=True, verbose_name='所属阶段')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('authority', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='cases.supervisingauthority', verbose_name='主管机关')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='cases.case', verbose_name='案件')),
            ],
            options={
                'verbose_name': '案件工作人员',
                'verbose_name_plural': '案件工作人员',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['case'], name='contacts_ca_case_id_dfd478_idx'), models.Index(fields=['authority'], name='contacts_ca_authori_857626_idx'), models.Index(fields=['stage'], name='contacts_ca_stage_0255c5_idx'), models.Index(fields=['role'], name='contacts_ca_role_a27f97_idx')],
            },
        ),
    ]
