# Generated by Django 6.0.6 on 2026-06-07 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message_hub', '0006_add_court_schedule_source_type'),
        ('organization', '0007_alter_lawyer_license_pdf'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='messagesource',
            index=models.Index(fields=['source_type'], name='message_hub_source__e80613_idx'),
        ),
    ]
