# Generated by Django 6.0.5 on 2026-05-24 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_ops', '0003_contenttask_tts_style_prompt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contenttask',
            name='discussion_speakers',
            field=models.JSONField(blank=True, default=list, help_text='多人讨论模式的角色列表，格式: [{name, role, style_prompt}]', verbose_name='讨论角色配置'),
        ),
        migrations.AddField(
            model_name='contenttask',
            name='output_mode',
            field=models.CharField(choices=[('narration', '单人叙事'), ('discussion', '多人讨论'), ('both', '两者都要')], default='narration', max_length=16, verbose_name='输出模式'),
        ),
        migrations.AddField(
            model_name='podcastepisode',
            name='content_source',
            field=models.CharField(choices=[('article', '文章'), ('discussion', '讨论稿')], default='article', max_length=16, verbose_name='内容来源'),
        ),
        migrations.AlterField(
            model_name='podcastepisode',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='content_ops.generatedarticle', verbose_name='文章'),
        ),
        migrations.CreateModel(
            name='DiscussionScript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('topic', models.TextField(blank=True, verbose_name='讨论主题')),
                ('review_status', models.CharField(choices=[('draft', '待审核'), ('approved', '已通过'), ('rejected', '已驳回')], default='draft', max_length=16, verbose_name='审核状态')),
                ('reviewer_notes', models.TextField(blank=True, verbose_name='审核备注')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('llm_model', models.CharField(blank=True, max_length=128, verbose_name='LLM模型')),
                ('token_usage', models.JSONField(blank=True, default=dict, verbose_name='Token用量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussion_scripts', to='content_ops.contenttask', verbose_name='任务')),
            ],
            options={
                'verbose_name': '讨论脚本',
                'verbose_name_plural': '讨论脚本',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='podcastepisode',
            name='discussion_script',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='content_ops.discussionscript', verbose_name='讨论脚本'),
        ),
        migrations.CreateModel(
            name='DiscussionTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker_name', models.CharField(max_length=64, verbose_name='说话人')),
                ('speaker_style_prompt', models.TextField(blank=True, verbose_name='VoiceDesign 音色描述')),
                ('text', models.TextField(verbose_name='对话内容')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='顺序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='content_ops.discussionscript', verbose_name='脚本')),
            ],
            options={
                'verbose_name': '对话轮次',
                'verbose_name_plural': '对话轮次',
                'ordering': ['order'],
            },
        ),
    ]
