# Generated by Django 6.0.6 on 2026-06-18 05:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocSpaceDocument",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255, verbose_name="文件名")),
                ("docspace_file_id", models.PositiveIntegerField(unique=True, verbose_name="DocSpace 文件 ID")),
                ("docspace_folder_id", models.PositiveIntegerField(verbose_name="DocSpace 文件夹 ID")),
                ("file_ext", models.CharField(default=".docx", max_length=16, verbose_name="文件类型")),
                ("content_length", models.PositiveIntegerField(default=0, verbose_name="文件大小(bytes)")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "last_editor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="last_edited_docspace_docs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="最后编辑者",
                    ),
                ),
                (
                    "lawyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="docspace_docs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="所属律师",
                    ),
                ),
            ],
            options={
                "verbose_name": "DocSpace 文档",
                "verbose_name_plural": "DocSpace 文档",
                "ordering": ["-updated_at"],
                "indexes": [models.Index(fields=["lawyer", "-updated_at"], name="docspace_do_lawyer__998f4b_idx")],
            },
        ),
    ]
