# Generated by Django 6.0.6 on 2026-06-12 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("evidence", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="hearingnote",
            name="evidence_he_case_id_fa3d32_idx",
        ),
        migrations.DeleteModel(
            name="HearingNote",
        ),
    ]
