# Generated by Django 6.0.6 on 2026-06-12 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0011_remove_smart_fill_proxy"),
        ("evidence", "0002_delete_hearingnote"),
    ]

    operations = [
        migrations.CreateModel(
            name="EvidenceItemProxy",
            fields=[],
            options={
                "verbose_name": "证据明细",
                "verbose_name_plural": "证据明细",
                "ordering": ["evidence_list", "order"],
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("documents.evidenceitem",),
        ),
        migrations.CreateModel(
            name="EvidenceListProxy",
            fields=[],
            options={
                "verbose_name": "证据清单",
                "verbose_name_plural": "证据清单",
                "ordering": ["case", "order"],
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("documents.evidencelist",),
        ),
    ]
