# Generated by Django 6.0.6 on 2026-06-12 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0025_alter_casefolderbinding_storage_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='模板名称')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='标识')),
                ('category', models.CharField(choices=[('litigation', '诉讼'), ('preservation', '保全'), ('enforcement', '执行')], max_length=20, verbose_name='类别')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('temporal_workflow_name', models.CharField(help_text="如 'SalesContractDisputeWorkflow'", max_length=200, verbose_name='Temporal Workflow 名称')),
                ('steps_schema', models.JSONField(help_text='[{"id":"collect_facts","name":"收集案件事实","type":"activity",...}]', verbose_name='步骤定义')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '流程模板',
                'verbose_name_plural': '流程模板',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temporal_workflow_id', models.CharField(max_length=200, unique=True, verbose_name='Temporal Workflow ID')),
                ('temporal_run_id', models.CharField(max_length=200, verbose_name='Temporal Run ID')),
                ('status', models.CharField(choices=[('running', 'Running'), ('waiting_human', 'Waiting Human'), ('waiting_event', 'Waiting Event'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('timed_out', 'Timed Out')], default='running', max_length=20, verbose_name='状态')),
                ('current_step_id', models.CharField(blank=True, default='', max_length=100, verbose_name='当前步骤')),
                ('result', models.JSONField(blank=True, null=True, verbose_name='运行结果')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='启动时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workflow_runs', to='cases.case', verbose_name='案件')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_workflows', to=settings.AUTH_USER_MODEL, verbose_name='发起人')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='workflow.workflowtemplate', verbose_name='流程模板')),
            ],
            options={
                'verbose_name': '工作流运行',
                'verbose_name_plural': '工作流运行',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='StepExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_id', models.CharField(max_length=100, verbose_name='步骤 ID')),
                ('step_name', models.CharField(max_length=200, verbose_name='步骤名称')),
                ('step_type', models.CharField(max_length=20, verbose_name='步骤类型')),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('waiting', 'Waiting'), ('skipped', 'Skipped')], max_length=20, verbose_name='状态')),
                ('input_data', models.JSONField(blank=True, default=dict, verbose_name='输入数据')),
                ('output_data', models.JSONField(blank=True, null=True, verbose_name='输出数据')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('attempts', models.IntegerField(default=0, verbose_name='尝试次数')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('workflow_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_executions', to='workflow.workflowrun', verbose_name='工作流运行')),
            ],
            options={
                'verbose_name': '步骤执行',
                'verbose_name_plural': '步骤执行',
                'ordering': ['started_at'],
                'unique_together': {('workflow_run', 'step_id')},
            },
        ),
    ]
