# Generated by Django 6.0.4 on 2026-04-29 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_historical_records'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['name'], name='cases_clien_name_119a2d_idx'),
        ),
    ]
