# Generated by Django 6.0.4 on 2026-05-02 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_client_cases_clien_name_119a2d_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='clientidentitydoc',
            index=models.Index(fields=['client', 'doc_type'], name='idx_iddoc_clt_doctype'),
        ),
    ]
