# Generated by Django 6.0.5 on 2026-05-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0008_add_client_type_index'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['phone'], name='cases_clien_phone_9b0559_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['is_our_client'], name='cases_clien_is_our__2bfc3f_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyclue',
            index=models.Index(fields=['client'], name='idx_propclue_client'),
        ),
        migrations.AddIndex(
            model_name='propertyclueattachment',
            index=models.Index(fields=['property_clue'], name='idx_pca_propclue'),
        ),
    ]
