# Generated by Django 6.0.5 on 2026-06-19 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0009_add_performance_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='fddbrsjhm_phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='法定代表人手机号（对应一张网 fddbrsjhm）'),
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='fddbrsjhm_phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='法定代表人手机号（对应一张网 fddbrsjhm）'),
        ),
    ]
