# Generated by Django 6.0.5 on 2026-05-10 03:31

import apps.core.filesystem.upload_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0013_courtsms_notification_results'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gsxtreporttask',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to=apps.core.filesystem.upload_paths.DatedUUIDPath('gsxt_reports'), verbose_name='报告文件'),
        ),
    ]
