# Generated by Django 6.0.6 on 2026-06-15 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0016_add_court_sms_dedup'),
        ('automation', '0017_add_court_sms_archived_folder_flag'),
    ]

    operations = [
    ]
