# Generated by Django 6.0.5 on 2026-06-16 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0019_remove_courtsms_automation__status_40c207_idx_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='courtsms',
            new_name='automation__content_eceb32_idx',
            old_name='automation__content_72497c_idx',
        ),
    ]
