# Generated by Django 6.0.4 on 2026-05-01 00:13

import apps.core.filesystem.upload_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0003_alter_lawyer_email_nullable"),
    ]

    operations = [
        migrations.AddField(
            model_name="lawyer",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.core.filesystem.upload_paths.DatedUUIDPath("avatars"),
                verbose_name="头像",
            ),
        ),
    ]
