# Generated by Django 6.0.5 on 2026-05-10 03:31

import apps.core.filesystem.storage
import apps.core.filesystem.upload_paths
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_email_nullable_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lawyer',
            name='license_pdf',
            field=models.FileField(blank=True, null=True, storage=apps.core.filesystem.storage.KeepOriginalNameStorage(), upload_to=apps.core.filesystem.upload_paths.DatedOriginalPath('lawyers/licenses'), validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='执业证文件'),
        ),
    ]
