# Generated by Django 6.0.5 on 2026-05-10 03:31

import apps.core.filesystem.upload_paths
import apps.evidence.models.evidence_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_add_archive_template_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidenceitem',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=apps.core.filesystem.upload_paths.DatedUUIDPath('evidence/files'), verbose_name='证据文件'),
        ),
        migrations.AlterField(
            model_name='evidencelist',
            name='merged_pdf',
            field=models.FileField(blank=True, help_text='将所有证据文件合并为一个PDF,便于打印和提交', null=True, storage=apps.evidence.models.evidence_storage.EvidenceFileStorage(base_url='/media/evidence/', location='/Users/huangsong21/Downloads/Coding/AI/FachuanHybridSystem/backend/apiSystem/media/evidence'), upload_to=apps.core.filesystem.upload_paths.DatedUUIDPath('evidence/merged'), verbose_name='合并PDF'),
        ),
        migrations.AlterField(
            model_name='generationtask',
            name='result_file',
            field=models.FileField(blank=True, null=True, upload_to=apps.core.filesystem.upload_paths.DatedUUIDPath('generated_documents'), verbose_name='生成文件'),
        ),
    ]
