# Generated by Django 6.0.5 on 2026-06-16 14:44

import apps.core.filesystem.upload_paths
import apps.evidence.models.evidence_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0013_remove_evidenceitem_documents_e_directi_22020a_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidencelist',
            name='merged_pdf',
            field=models.FileField(blank=True, help_text='将所有证据文件合并为一个PDF,便于打印和提交', null=True, storage=apps.evidence.models.evidence_storage.EvidenceFileStorage(base_url='/media/evidence/', location='C:\\Users\\Administrator\\Downloads\\fc-sujun\\FachuanHybridSystem\\backend\\apiSystem\\media\\evidence'), upload_to=apps.core.filesystem.upload_paths.DatedUUIDPath('evidence/merged'), verbose_name='合并PDF'),
        ),
    ]
