# Generated by Django 6.0.6 on 2026-06-19 18:35

import apps.core.filesystem.upload_paths
import apps.evidence.models.evidence_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0015_alter_documenttemplate_case_sub_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidencelist',
            name='merged_pdf',
            field=models.FileField(blank=True, help_text='将所有证据文件合并为一个PDF,便于打印和提交', null=True, storage=apps.evidence.models.evidence_storage.EvidenceFileStorage(base_url='/media/evidence/', location='/app/apiSystem/media/evidence'), upload_to=apps.core.filesystem.upload_paths.DatedUUIDPath('evidence/merged'), verbose_name='合并PDF'),
        ),
    ]
