# Generated by Django 6.0.4 on 2026-05-07 10:17

import apps.core.filesystem.upload_paths
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeChatAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='账号名称')),
                ('mp_url', models.URLField(default='https://mp.weixin.qq.com', verbose_name='公众号后台地址')),
                ('cookie_path', models.CharField(blank=True, default='', max_length=500, verbose_name='Cookie 存储路径')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wechat_accounts', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '公众号账号',
                'verbose_name_plural': '公众号账号',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PublishTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='文章标题')),
                ('content_md', models.TextField(verbose_name='Markdown 内容')),
                ('content_html', models.TextField(blank=True, default='', verbose_name='HTML 内容')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to=apps.core.filesystem.upload_paths.DatedUUIDPath('wechat_mp/covers'), verbose_name='封面图')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('logging_in', '登录中'), ('editing', '编辑中'), ('publishing', '发布中'), ('success', '成功'), ('failed', '失败')], default='pending', max_length=20, verbose_name='任务状态')),
                ('save_as_draft', models.BooleanField(default=True, verbose_name='保存为草稿')),
                ('result_data', models.JSONField(blank=True, default=dict, verbose_name='结果数据')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('queue_task_id', models.CharField(blank=True, default='', max_length=64, verbose_name='队列任务ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wechat_publish_tasks', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publish_tasks', to='wechat_mp.wechataccount', verbose_name='公众号账号')),
            ],
            options={
                'verbose_name': '发布任务',
                'verbose_name_plural': '发布任务',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='wechat_mp_p_status_d53c84_idx'), models.Index(fields=['account', '-created_at'], name='wechat_mp_p_account_339ac6_idx')],
            },
        ),
    ]
