# Generated by Django 6.0.5 on 2026-05-24 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wechat_mp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wechataccount',
            name='cookie_path',
        ),
    ]
