# Generated by Django 6.0.5 on 2026-05-24 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wechat_mp', '0002_remove_cookie_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishtask',
            name='format_method',
            field=models.CharField(choices=[('rule', '规则排版'), ('llm', 'AI 排版')], default='rule', max_length=20, verbose_name='排版方式'),
        ),
    ]
