# Generated by Django 6.0.4 on 2026-04-29 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_client_cases_clien_name_119a2d_idx'),
        ('contracts', '0025_add_content_hash_and_classification_rule'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='contractparty',
            index=models.Index(fields=['client'], name='contracts_c_client__6764de_idx'),
        ),
    ]
