# Generated by Django 6.0.4 on 2026-05-02 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0026_contractparty_contracts_c_client__6764de_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientpaymentrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='historicalclientpaymentrecord',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, default='', help_text='SHA-256, 用于去重', max_length=64, verbose_name='内容哈希'),
        ),
        migrations.AlterField(
            model_name='finalizedmaterial',
            name='file_path',
            field=models.CharField(db_index=True, max_length=500, verbose_name='文件路径'),
        ),
    ]
