# Generated by Django 6.0.4 on 2026-05-02 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0027_p2_model_improvements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractpayment',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='contracts.contract', verbose_name='合同'),
        ),
    ]
