# Generated by Django 6.0.6 on 2026-06-10 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0032_alter_contractfolderbinding_storage_type'),
        ('core', '0010_add_device_code_pending_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracttypefolderrootpreset',
            name='storage_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cloudstorageaccount', verbose_name='云存储账号'),
        ),
        migrations.AddField(
            model_name='contracttypefolderrootpreset',
            name='storage_type',
            field=models.CharField(default='local', help_text='local / webdav / s3 / onedrive / google_drive / dropbox', max_length=20, verbose_name='存储类型'),
        ),
    ]
