# Generated by Django 6.0.4 on 2026-04-30 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("legal_research", "0009_add_advanced_query_and_filters"),
    ]

    operations = [
        migrations.AlterField(
            model_name="legalresearchtask",
            name="llm_backend",
            field=models.CharField(default="", max_length=64, verbose_name="LLM后端"),
        ),
    ]
