# Generated by Django 6.0.4 on 2026-05-06 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_research', '0010_llm_backend_default_empty'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalresearchtask',
            name='search_url',
            field=models.URLField(blank=True, max_length=2000, verbose_name='WKInfo搜索URL'),
        ),
    ]
