# Generated by Django 6.0.5 on 2026-05-10 03:31

import apps.core.filesystem.upload_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_research', '0011_add_search_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legalresearchresult',
            name='pdf_file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=apps.core.filesystem.upload_paths.EntityIdPath('legal_research', 'pk'), verbose_name='PDF文件'),
        ),
    ]
