# Generated by Django 6.0.5 on 2026-05-11 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal_research', '0012_alter_legalresearchresult_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalresearchtask',
            name='llm_scoring_concurrency',
            field=models.PositiveIntegerField(default=5, help_text='同时并发的 LLM 评分线程数。默认 5，397B 模型建议 100。', verbose_name='LLM评分并发数'),
        ),
    ]
